In [1]:
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x1262ef773a0>)

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [4]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [5]:
climate_data.shape

(10000, 3)

In [6]:
weights = np.array([0.3,0.2,0.5])

In [7]:
yields= climate_data @ weights

In [8]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [9]:
yields.shape

(10000,)

In [10]:
import numpy as np

In [11]:
climate_results = np.concatenate((climate_data,yields.reshape(10000,1)), axis=1)

In [12]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])